In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sbn

In [3]:
ppp_dataset = pd.read_csv('PPP_Loans_to_Connecticut_Businesses.csv', dtype = object)

In [4]:
ppp_dataset.head()

,LoanRange,LoanAmount,BusinessName,Address,City,State,Zip,NAICSCode,BusinessType,RaceEthnicity,Gender,Veteran,NonProfit,JobsReported,DateApproved,Lender,CD
0,a $5-10 million,NaN,"AFFINECO, LLC",855 MAIN ST,BRIDGEPORT,CT,6604,561720,Limited Liability Company(LLC),Unanswered,Unanswered,Unanswered,NaN,500,04/13/2020,"People's United Bank, National Association",CT-04
1,a $5-10 million,NaN,"ALLIED PRINTING SERVICES, INC.",1 ALLIED WAY,MANCHESTER,CT,6042,323111,Subchapter S Corporation,Unanswered,Unanswered,Unanswered,NaN,368,04/05/2020,"People's United Bank, National Association",CT-01
2,a $5-10 million,NaN,AMERICAN CUSTOMER CARE INC,225 N Main Street,BRISTOL,CT,6010,561422,Corporation,Unanswered,Male Owned,Non-Veteran,NaN,NaN,04/28/2020,Israel Discount Bank of New York,CT-01
3,a $5-10 million,NaN,"APPLE CENTRAL, LLC",170 Mason Street,GREENWICH,CT,6830,722511,Limited Liability Company(LLC),Unanswered,Unanswered,Unanswered,NaN,NaN,04/14/2020,First Horizon Bank,CT-04
4,a $5-10 million,NaN,"BL COMPANIES, INC.",355 Research Parkway,Meriden,CT,6450,541330,Subchapter S Corporation,Unanswered,Unanswered,Unanswered,NaN,NaN,04/15/2020,"Citizens Bank, National Association",CT-05